Vous pouvez vous abonner à cet agenda public [[https://owncloud.data.gouv.fr/index.php/apps/calendar/p/YAjeWZjoGFgs2dLp/agenda-tech-ext][en ligne]].

* FOSDEM - https://fosdem.org/2019/
  :PROPERTIES:
  :ID:       c457dfc5-3475-490f-a7bf-830c31ecb06b
  :END:
  <2019-02-02 sam.>-<2019-02-03 dim.>

FOSDEM is a free event for software developers to meet, share ideas
and collaborate.

Every year, thousands of developers of free and open source software
from all over the world gather at the event in Brussels.

* Conférence SATRDAY - https://paris2019.satrdays.org/
  SCHEDULED: <2019-02-23 sam. 09:00-17:30>
  :PROPERTIES:
  :LOCATION: AgroParisTech
  :ID:       c334f5d4-5dbf-4248-be26-5aae4523e145
  :END:

https://paris2019.satrdays.org/

SatRDays are community-led, regional conferences to support
collaboration, networking and innovation within the R community.

satRday Paris 2019 will be held on Saturday February 23th 2019 from
09.00 to 17.30.

This event will take place at AgroParisTech.

* Journées du Logiciel Libre de Lyon - https://www.jdll.org/
  :PROPERTIES:
  :ID:       6a5c7e3c-be33-45f2-9142-5f7e96cbd03b
  :END:
  <2019-04-06 sam.>-<2019-04-07 dim.>

Les Journées du Logiciel Libre de Lyon (JdLL) sont organisées par
l’Espace Public Numérique de la Maison Pour Tous des Rancy, l’Aldil
(Association Lyonnaise pour le Développement de l’Informatique Libre),
Illyse (fournisseur d'accès à Internet associatif à Lyon et
Saint-Étienne), et la licence Colibre de l’université Lumière Lyon 2.
Ce réseau d’associations et d’établissements mène tout au long de
l’année des actions autour de la découverte des pratiques du
numérique. Celles-ci visent à accroitre l’inclusion numérique par un
travail d’accompagnement et de médiation auprès des seniors, des
enfants et des adultes.

Pour sa 20e édition, les Journées du Logiciel Libre se tiendront les 6
et 7 avril 2019 à la Maison Pour tous des Rancy, dans le 3e
arrondissement de Lyon. Le thème de cette année portera sur les liens
entre écologie et numérique, qui fait écho aux interrogations des
citoyens d’aujourd’hui.

* Nancy Ville Numérique "Numérique et Transition Ecologique"
  SCHEDULED: <2019-06-04 mar.>
  :PROPERTIES:
  :ID:       078e0cfc-2978-49eb-8a8d-62ff8f33c974
  :END:

L'équipe Nancy Ville Numérique organise la deuxième édition des RDV
Nancy Ville Numérique avec pour thème cette année Numérique et
Transition Ecologique. Cette journée d'échanges et de tables rondes
aura lieu le mardi 4 juin et est à destination principalement des
agents de la fonction publique mais est ouverte à tous.

Les thèmes abordés seront :
- GREEN IT
- Eco-conception
- Recyclage
- Smart City et numérique

Et peut-être d'autres suivant les idées de nos futurs intervenants.

* Conférence PyParis - http://pyparis.org
  :PROPERTIES:
  :LOCATION: EPITA, Paris / Le Kremlin Bicêtre, France
  :ID:       707396dd-6d61-4f0c-b69b-c821d819e29f
  :END:
  <2018-11-14 mer.>-<2018-11-15 jeu.>

http://pyparis.org

A conference for developers and users of Python

The PyParis conference is a gathering of users and developers of the
Python programming language.

The goals are to provide Python enthusiasts a place to share ideas and
learn from each other about how best to apply the language and tools
to ever-evolving challenges in the vast realm of application
development, scientific computing, data analytics, education, cloud,
devops...

